### ISSUE TITLE
Remove DevExpress dependencies

### ISSUE THREAD

**Issue by IanKemp** [awaescher/Fusion#17]
DevExpress is extremely powerful, but also extremely heavyweight (for example, `DevExpress.Utils.v19.2.dll` in the latest release is an entire TWENTY MEGABYTES). For such a simple application that uses such a small subset of the DevExpress features, I'm sure that an open-source component or two would offer almost the same functionality at a much lesser cost (for example: https://github.com/swharden/ScottPlot for graphing).

This would also solve #5.

**Comment by awaescher** [comment]
Thanks for the suggestion but I chose DevExpress mostly because I wanted to build a compelling UI.
Saving some megabytes would be nice but I don‘t see a problem having a ~35MB download these days.

I would have to search for new components, learn & translate to their concept and build an entirely new UI for Fusion++. Efforts I am not willing to throw in just to make a smaller and likely less beautiful app.
